version: '3.7'

services:
  api:
    build: .
    volumes: 
      &api-volumes
      - ~/.ssh:/root/.ssh
      - ~/.bash_history:/root/.bash_history
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    environment: 
      &api-environment
      DJANGO_ENV: dev
      DJANGO_SECRET_KEY: 'django-insecure-zuq!tp7e*loq29*f)lp^#hvgi$q@*pwk@+m3(z@v(^@z@)t(a4'

      DATABASE_NAME: postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: db
      DATABASE_PORT: 5432

      STRIPE_PUBLIC_KEY: pk_test_51Mc30vD79bunDAajR0DeevMyE749ShgZQ3FlsbggP1j8yv0o7hIcZp2uOQfWq2E0jWhZW1Z0RSFU23EWa4Ffkci400oIYPMVH4
      STRIPE_SECRET_KEY: sk_test_51Mc30vD79bunDAajByhclVWY3AFiidpKc3mS4rGCwdz3HuhvOj5FRTB7jHhOz07NpTQ6F16MInFFbVezdjqOFwCB00AVVQQjLd
    command: python manage.py runserver 0.0.0.0:8000

  db:
    image: postgres:11.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
volumes:	
  postgres_data: